{
 "title": "Test Cluster Node Usage",
 "tags": [
  "Slurm",
  "Production"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Cluster Node Usage",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Description**\n\nShows status of overall cluster usage drawn from slurm itself.\n\n**Node State**\n\nThis plot shows current number of nodes in different states.\n\n**IDLE**: Means nothing is running on the node.\n\n**MIXED**: Means the node is partially allocated in terms of core count.  Note all the memory could be allocated on the node but still show up as MIXED.\n\n**ALLOCATED**: Node is fully allocated in terms of cores.\n\n**DRAIN**: Node is in the process of draining.\n\n**DOWN**: Node is down or fully drained.\n\n**COMPLETING**: Node is currently working on closing out jobs.\n\n**RESERVED**: Node is reserved for use but is IDLE.\n\n**Core/Memory/GPU Usage**\n\nShows the amount of cores/memory that are allocated and in use.\n\n**Node Occupation**\n\nSince looking at pure core, memory, or gpu allocation is misleading in terms of actual cluster usage, this plot shows occupation instead.  Occupation is `MAX(CPUAlloc/CPUTot, MemAlloc/MemTot, GPUAlloc/GPUTot)` summed across all the nodes.  The idea is that a node that has its memory fully utilized effectively has all its cores used as you can't schedule any more jobs.  Similarly a node that has all its cores used cannot allocate any memory even though it is available. For a GPU node, a full usage of the GPU's is effectively full occupation even if the CPU and memory are not fully used.  This metric should hopefully provide a better estimate of cluster usage.  Ideally it should be equal to the number of nodes (assuming no down nodes).\n\n**Percent Utilization**\n\nThis is the amount of the cluster that is utilized based on the average Node Occupation."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Node State",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"alloctot\"}",
     "legendFormat": "Allocated Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.alloctot, 'Allocated Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"downtot\"}",
     "legendFormat": "Down Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.downtot, 'Down Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"draintot\"}",
     "legendFormat": "Draining Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.draintot, 'Draining Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"idletot\"}",
     "legendFormat": "Idle Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.idletot, 'Idle Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"mixedtot\"}",
     "legendFormat": "Mixed Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.mixedtot, 'Mixed Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"restot\"}",
     "legendFormat": "Reserved Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.restot, 'Reserved Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"plannedtot\"}",
     "legendFormat": "Planned Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.plannedtot, 'Planned Nodes')"
    }
   ]
  },
  {
   "title": "Percent Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Occupation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"nodetot\"}",
     "legendFormat": "Total Number of Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.nodetot, 'Total Number of Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"peralloc\"}",
     "legendFormat": "Node Occupation",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.peralloc, 'Node Occupation')"
    }
   ]
  },
  {
   "title": "Node State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"nodetot\"}",
     "legendFormat": "Total Number of Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.nodetot, 'Total Number of Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"alloctot\"}",
     "legendFormat": "Allocated Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.alloctot, 'Allocated Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"comptot\"}",
     "legendFormat": "Completing Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.comptot, 'Completing Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"downtot\"}",
     "legendFormat": "Down Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.downtot, 'Down Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"draintot\"}",
     "legendFormat": "Draining Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.draintot, 'Draining Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"mixedtot\"}",
     "legendFormat": "Mixed Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.mixedtot, 'Mixed Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"idletot\"}",
     "legendFormat": "Idle Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.idletot, 'Idle Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"restot\"}",
     "legendFormat": "Reserved Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.restot, 'Reserved Nodes')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"plannedtot\"}",
     "legendFormat": "Planned Nodes",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.plannedtot, 'Planned Nodes')"
    }
   ]
  },
  {
   "title": "Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"cputot\"}",
     "legendFormat": "Total Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.cputot, 'Total Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"cpualloc\"}",
     "legendFormat": "Allocated Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.cpualloc, 'Allocated Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"cpuload\"}",
     "legendFormat": "Used Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.cpuload, 'Used Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"downcpu\"}",
     "legendFormat": "Down Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.downcpu, 'Down Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"draincpu\"}",
     "legendFormat": "Drain Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.draincpu, 'Drain Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"rescpu\"}",
     "legendFormat": "Reserved Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.rescpu, 'Reserved Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"plannedcpu\"}",
     "legendFormat": "Planned Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.plannedcpu, 'Planned Cores')"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"realmem\"}",
     "legendFormat": "Total Memory",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.realmem, 'Total Memory')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"memalloc\"}",
     "legendFormat": "Allocated Memory",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.memalloc, 'Allocated Memory')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"memload\"}",
     "legendFormat": "Used Memory",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.memload, 'Used Memory')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"downmem\"}",
     "legendFormat": "Down Memory",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.downmem, 'Down Memory')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"drainmem\"}",
     "legendFormat": "Drain Memory",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.drainmem, 'Drain Memory')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"resmem\"}",
     "legendFormat": "Reserved Memory",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.resmem, 'Reserved Memory')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"plannedmem\"}",
     "legendFormat": "Planned Memory",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.plannedmem, 'Planned Memory')"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"gputot\"}",
     "legendFormat": "Total GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.gputot, 'Total GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"gpualloc\"}",
     "legendFormat": "Allocated GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.gpualloc, 'Allocated GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"downgpu\"}",
     "legendFormat": "Down GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.downgpu, 'Down GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"draingpu\"}",
     "legendFormat": "Drain GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.draingpu, 'Drain GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"resgpu\"}",
     "legendFormat": "Reserved GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.resgpu, 'Reserved GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"plannedgpu\"}",
     "legendFormat": "Planned GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.plannedgpu, 'Planned GPUs')"
    }
   ]
  },
  {
   "title": "Core Usage",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "Plots of usage of different core types.  The memory usage is reported number of effective cores used."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ice Lake Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcpuicelake\"}",
     "legendFormat": "Total Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcpuicelake, 'Total Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucpuicelake\"}",
     "legendFormat": "Allocated Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucpuicelake, 'Allocated Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umemicelake\"}",
     "legendFormat": "Effective Allocated Memory in Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umemicelake, 'Effective Allocated Memory in Cores')"
    }
   ]
  },
  {
   "title": "Cascade Lake Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcpucascadelake\"}",
     "legendFormat": "Total Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcpucascadelake, 'Total Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucpucascadelake\"}",
     "legendFormat": "Allocated Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucpucascadelake, 'Allocated Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umemcascadelake\"}",
     "legendFormat": "Effective Allocated Memory in Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umemcascadelake, 'Effective Allocated Memory in Cores')"
    }
   ]
  },
  {
   "title": "Rome Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcpurome\"}",
     "legendFormat": "Total Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcpurome, 'Total Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucpurome\"}",
     "legendFormat": "Allocated Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucpurome, 'Allocated Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umemrome\"}",
     "legendFormat": "Effective Allocated Memory in Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umemrome, 'Effective Allocated Memory in Cores')"
    }
   ]
  },
  {
   "title": "Milan Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcpumilan\"}",
     "legendFormat": "Total Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcpumilan, 'Total Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucpumilan\"}",
     "legendFormat": "Allocated Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucpumilan, 'Allocated Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umemmilan\"}",
     "legendFormat": "Effective Allocated Memory in Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umemmilan, 'Effective Allocated Memory in Cores')"
    }
   ]
  },
  {
   "title": "Skylake Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcpuskylake\"}",
     "legendFormat": "Total Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcpuskylake, 'Total Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucpuskylake\"}",
     "legendFormat": "Allocated Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucpuskylake, 'Allocated Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umemskylake\"}",
     "legendFormat": "Effective Allocated Memory in Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umemskylake, 'Effective Allocated Memory in Cores')"
    }
   ]
  },
  {
   "title": "Broadwell Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcpubroadwell\"}",
     "legendFormat": "Total Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcpubroadwell, 'Total Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucpubroadwell\"}",
     "legendFormat": "Allocated Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucpubroadwell, 'Allocated Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umembroadwell\"}",
     "legendFormat": "Effective Allocated Memory in Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umembroadwell, 'Effective Allocated Memory in Cores')"
    }
   ]
  },
  {
   "title": "Haswell Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcpuhaswell\"}",
     "legendFormat": "Total Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcpuhaswell, 'Total Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucpuhaswell\"}",
     "legendFormat": "Allocated Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucpuhaswell, 'Allocated Cores')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umemhaswell\"}",
     "legendFormat": "Effective Allocated Memory in Cores",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umemhaswell, 'Effective Allocated Memory in Cores')"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "options": { "content": "GPU usage by different type." },
   "targets": [
    {}
   ]
  },
  {
   "title": "A100 Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgpua100\"}",
     "legendFormat": "Total GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgpua100, 'Total GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugpua100\"}",
     "legendFormat": "Allocated GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugpua100, 'Allocated GPUs')"
    }
   ]
  },
  {
   "title": "V100 Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgpuv100\"}",
     "legendFormat": "Total GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgpuv100, 'Total GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugpuv100\"}",
     "legendFormat": "Allocated GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugpuv100, 'Allocated GPUs')"
    }
   ]
  },
  {
   "title": "RTX2080ti Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgpurtx2080ti\"}",
     "legendFormat": "Total GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgpurtx2080ti, 'Total GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugpurtx2080ti\"}",
     "legendFormat": "Allocated GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugpurtx2080ti, 'Allocated GPUs')"
    }
   ]
  },
  {
   "title": "P100 Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgpup100\"}",
     "legendFormat": "Total GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgpup100, 'Total GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugpup100\"}",
     "legendFormat": "Allocated GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugpup100, 'Allocated GPUs')"
    }
   ]
  },
  {
   "title": "A100 MIG Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgpua100mig\"}",
     "legendFormat": "Total GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgpua100mig, 'Total GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugpua100mig\"}",
     "legendFormat": "Allocated GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugpua100mig, 'Allocated GPUs')"
    }
   ]
  },
  {
   "title": "A40 Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgpua40\"}",
     "legendFormat": "Total GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgpua40, 'Total GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugpua40\"}",
     "legendFormat": "Allocated GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugpua40, 'Allocated GPUs')"
    }
   ]
  },
  {
   "title": "TitanX Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgputitanx\"}",
     "legendFormat": "Total GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgputitanx, 'Total GPUs')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugputitanx\"}",
     "legendFormat": "Allocated GPUs",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugputitanx, 'Allocated GPUs')"
    }
   ]
  },
  {
   "title": "TRES and GFLOps",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 46 },
   "options": {
    "content": "These graphs show effective TRES and GFLOps usage.\n\nTRES is based off our normal weighting scheme.  This includes core, gpu, and memory TRES.  This should give a better view of our actual compute capability.\n\nGFLOps is based on our translation from TRES to GFLOps.  This only includes core and gpu.  This is based on theoretic peak, not actual GFLOps so numbers should be taken with a grain of salt."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current TRES Fractional Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucputres\"}",
     "legendFormat": "Core TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucputres, 'Core TRES')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umemtres\"}",
     "legendFormat": "Memory TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umemtres, 'Memory TRES')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugputres\"}",
     "legendFormat": "GPU TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugputres, 'GPU TRES')"
    }
   ]
  },
  {
   "title": "Percent Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Total TRES Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ttres\"}",
     "legendFormat": "Total TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ttres, 'Total TRES')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"utres\"}",
     "legendFormat": "Allocated TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.utres, 'Total TRES')"
    }
   ]
  },
  {
   "title": "CPU TRES Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcputres\"}",
     "legendFormat": "Total TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcputres, 'Total TRES')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucputres\"}",
     "legendFormat": "Allocated TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucputres, 'Allocated TRES')"
    }
   ]
  },
  {
   "title": "GPU TRES Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgputres\"}",
     "legendFormat": "Total TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgputres, 'Total TRES')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugputres\"}",
     "legendFormat": "Allocated TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugputres, 'Allocated TRES')"
    }
   ]
  },
  {
   "title": "Memory TRES Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tmemtres\"}",
     "legendFormat": "Total TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tmemtres, 'Total TRES')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"umemtres\"}",
     "legendFormat": "Allocated TRES",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.umemtres, 'Allocated TRES')"
    }
   ]
  },
  {
   "title": "Current GFLOps Fractional Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucgflops\"}",
     "legendFormat": "CPU GFLOps",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucgflops, 'CPU GFLOps')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"uggflops\"}",
     "legendFormat": "GPU GFLOps",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.uggflops, 'GPU GFLOps')"
    }
   ]
  },
  {
   "title": "Percent Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Total GFLOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tgflops\"}",
     "legendFormat": "Total GFLOps",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tgflops, 'Total GFLOps')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ugflops\"}",
     "legendFormat": "Allocated GLOps",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ugflops, 'Allocated GFLOps')"
    }
   ]
  },
  {
   "title": "CPU GFLOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tcgflops\"}",
     "legendFormat": "Total GFLOps",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tcgflops, 'Total GFLOps')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"ucgflops\"}",
     "legendFormat": "Allocated GFLOps",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.ucgflops, 'Allocated GFLOps')"
    }
   ]
  },
  {
   "title": "GPU GFLOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "lsload{host=\"slurm-test\", field=\"tggflops\"}",
     "legendFormat": "Total GFLOps",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.tggflops, 'Total GFLOps')"
    },
    {
     "expr": "lsload{host=\"slurm-test\", field=\"uggflops\"}",
     "legendFormat": "Allocated GFLOps",
     "target": "alias(diamond.holyoke.holy-slurm02.lsload.uggflops, 'Allocated GFLOps')"
    }
   ]
  }
 ]
}