{
 "title": "Test Cluster Scheduler Statistics",
 "tags": [
  "Slurm",
  "Production"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Slurmctld Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Slurmctld Execution",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "content": "**VALUES ARE RESET AT MIDNIGHT UTC TIME BY DEFAULT.**\n\n**Server thread count**  The number of current active slurmctld threads. A high number would mean a high load processing events like job submissions, jobs dispatching, jobs completing, etc.  If this  is often close to `MAX_SERVER_THREADS (256)` it could point to a potential bottleneck.\n\n**Agent queue size**  Slurm design has scalability in mind and sending messages to thousands of nodes is not a trivial task. The agent mechanism helps to control communication between the slurm daemons and the controller for a best effort. If (**agent queue size** + `AGENT_THREAD_COUNT` + 2) > `MAX_SERVER_THREADS`, there could be some delays affecting jobs management.  `AGENT_THREAD_COUNT (10)`\n\n**Jobs submitted**  Number of jobs submitted since last reset\n\n**Jobs started**  Number of jobs started since last reset. This  includes  backfilled  jobs.\n\n**Jobs completed**  Number of jobs completed since last reset.\n\n**Jobs canceled** Number of jobs canceled since last reset.\n\n**Jobs failed** Number of jobs failed since last reset.\n"
    }
   ]
  },
  {
   "title": "Slurmctld Stats / Job State Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Thread Count / Agent Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"server_thread_count\"}",
     "legendFormat": "Server Thread Count",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.server_thread_count, 'Server Thread Count')"
    },
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"agent_queue_size\"}",
     "legendFormat": "Agent Queue Size",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.agent_queue_size, 'Agent Queue Size')"
    }
   ]
  },
  {
   "title": "Jobs Submitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"jobs_submitted\"}",
     "legendFormat": "Jobs Submitted",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.jobs_submitted, 'Jobs Submitted')"
    },
    {
     "expr": "idelta(sdiag{host=\"slurm-test\", field=\"jobs_submitted\"}[$__interval])",
     "legendFormat": "Jobs Submitted per second",
     "target": "alias(perSecond(diamond.holyoke.holy-slurm02.sdiag.jobs_submitted), 'Jobs Submitted per second')"
    }
   ]
  },
  {
   "title": "Jobs Started",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"jobs_started\"}",
     "legendFormat": "Jobs Started",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.jobs_started, 'Jobs Started')"
    },
    {
     "expr": "idelta(sdiag{host=\"slurm-test\", field=\"jobs_started\"}[$__interval])",
     "legendFormat": "Jobs Started per second",
     "target": "alias(perSecond(diamond.holyoke.holy-slurm02.sdiag.jobs_started), 'Jobs Started per second')"
    }
   ]
  },
  {
   "title": "Jobs Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"jobs_completed\"}",
     "legendFormat": "Jobs Completed",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.jobs_completed, 'Jobs Completed')"
    },
    {
     "expr": "idelta(sdiag{host=\"slurm-test\", field=\"jobs_completed\"}[$__interval])",
     "legendFormat": "Jobs Completed per second",
     "target": "alias(perSecond(diamond.holyoke.holy-slurm02.sdiag.jobs_completed), 'Jobs Completed per second')"
    }
   ]
  },
  {
   "title": "Jobs Canceled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"jobs_canceled\"}",
     "legendFormat": "Jobs Canceled",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.jobs_canceled, 'Jobs Canceled')"
    },
    {
     "expr": "idelta(sdiag{host=\"slurm-test\", field=\"jobs_canceled\"}[$__interval])",
     "legendFormat": "Jobs Canceled per second",
     "target": "alias(perSecond(diamond.holyoke.holy-slurm02.sdiag.jobs_canceled), 'Jobs Canceled per second')"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"jobs_failed\"}",
     "legendFormat": "Jobs Failed",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.jobs_failed, 'Jobs Failed')"
    }
   ]
  },
  {
   "title": "Main Scheduler Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Main Scheduling Algorithm",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "content": "A  scheduling cycle implies to get the job_write_lock lock, then trying to get resources for jobs pending, starting from the most priority one and going in descendent order. Once a job can not get the resources the loop keeps going but just for jobs requesting other partitions. Jobs with dependencies or affected by accounts limits are not processed.\n\n**Last cycle**  Time in microseconds for last scheduling cycle.\n\n**Max cycle**  Time in microseconds for the maximum scheduling cycle since last reset.\n\n**Total cycles** Number of scheduling cycles since last reset. Scheduling is done in periodically and when a job is submitted or a job is completed.\n\n**Mean cycle**  Mean of scheduling cycles since last reset.\n\n**Mean depth cycle**  Mean of cycle depth.  Depth means number of jobs processed in a scheduling cycle.\n\n**Cycles per minute**  Counter of scheduling executions per minute\n\n**Last queue length**  Length of jobs pending queue.\n"
    }
   ]
  },
  {
   "title": "Main Scheduler Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last Cycle Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"main_last_cycle\"}",
     "legendFormat": "Time for last scheduling cycle",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.main_last_cycle, 'Time for last scheduling cycle')"
    }
   ]
  },
  {
   "title": "Total Cycles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"main_total_cycles\"}",
     "legendFormat": "Number of scheduling cycles",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.main_total_cycles, 'Number of scheduling cycles')"
    },
    {
     "expr": "idelta(sdiag{host=\"slurm-test\", field=\"main_total_cycles\"}[$__interval])",
     "legendFormat": "Scheduling cycles / second",
     "target": "alias(perSecond(diamond.holyoke.holy-slurm02.sdiag.main_total_cycles), 'Scheduling cycles / second')"
    }
   ]
  },
  {
   "title": "Mean Cycle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"main_mean_cycle\"}",
     "legendFormat": "Mean of scheduling cycles",
     "target": "alias(scale(diamond.holyoke.holy-slurm02.sdiag.main_mean_cycle, 0.000001), 'Mean of scheduling cycles')"
    }
   ]
  },
  {
   "title": "Mean Depth Cycle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"main_mean_depth_cycle\"}",
     "legendFormat": "Mean of jobs processed in a scheduling cycle",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.main_mean_depth_cycle, 'Mean of jobs processed in a scheduling cycle')"
    }
   ]
  },
  {
   "title": "Cycles per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"main_cycles_per_minute\"}",
     "legendFormat": "Scheduling executions per minute",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.main_cycles_per_minute, 'Scheduling executions per minute')"
    }
   ]
  },
  {
   "title": "Last Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"main_last_queue_length\"}",
     "legendFormat": "Length of jobs pending queue",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.main_last_queue_length, 'Length of jobs pending queue')"
    }
   ]
  },
  {
   "title": "Backfill Scheduler Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backfilling Scheduling",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "content": "A backfilling scheduling cycle implies to get locks for jobs, nodes and partitions objects then trying to get resources for jobs pending.  Jobs are processed based on priorities.  If a job can not get resources the algorithm calculates when it could get them obtaining a future start time for the job.  Then next job is processed and the algorithm tries to get resources for that job but avoiding to affect the previous ones, and again it calculates the future start time if not current resources available. The backfilling algorithm takes more time for each new job to process since more priority jobs can not be affected. The algorithm itself takes measures for avoiding a long execution cycle and for taking all the locks for too long.\n\n**Total backfilled jobs (since last slurm start)**  Number of jobs started thanks to backfilling since last slurm start.\n\n**Total backfilled jobs (since last stats cycle start)** Number of jobs started thanks to backfilling since last time stats where reset. By default these values are reset at midnight UTC time.\n\n**Total cycles**  Number of scheduling cycles since last reset\n\n**Last cycle**  Time in microseconds of last backfilling cycle.  It counts only execution time removing sleep time inside a scheduling cycle when it takes too much time.  Note that locks are released during the sleep time so that other work can proceed.\n\n**Max cycle**  Time in microseconds of maximum backfilling cycle execution since last reset.   It counts only execution time removing sleep time inside a scheduling cycle when it takes too much time.   Note that locks are released during the sleep time so that other work can proceed.\n\n**Mean cycle**  Mean of backfilling scheduling cycles in microseconds since last reset\n\n**Last depth cycle**  Number of processed jobs during last backfilling scheduling cycle.  It counts every process even if it has no option to execute due to dependencies or limits.\n\n**Last depth cycle (try sched)**  Number of processed jobs during last backfilling scheduling cycle.  It counts only processes with a chance to run waiting for available resources.  These jobs are which makes the backfilling algorithm heavier.\n\n**Depth Mean**  Mean of processed jobs during backfilling scheduling cycles since last reset.\n\n**Depth Mean (try sched)**  Mean of processed jobs during backfilling scheduling cycles since last reset.  It counts only processes with a chance to run waiting for available resources.  These jobs are which makes the backfilling algorithm heavier.\n\n**Last queue length**  Number of jobs pending to be processed by backfilling algorithm.  A job appears as much times as partitions it requested.\n\n**Queue length Mean**  Mean of jobs pending to be processed by backfilling algorithm."
    }
   ]
  },
  {
   "title": "Backfill Scheduler Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total backfilled jobs (since last slurm start)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"bf_total_jobs_since_slurm_start\"}",
     "legendFormat": "Backfill Jobs Started",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.bf_total_jobs_since_slurm_start, 'Backfill Jobs Started')"
    }
   ]
  },
  {
   "title": "Total backfilled jobs (since last stats cycle start)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"bf_total_jobs_since_cycle_start\"}",
     "legendFormat": "Backfill Jobs Started",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.bf_total_jobs_since_cycle_start, 'Backfill Jobs Started')"
    },
    {
     "expr": "idelta(sdiag{host=\"slurm-test\", field=\"bf_total_jobs_since_cycle_start\"}[$__interval])",
     "legendFormat": "Backfill Jobs Started per second",
     "target": "alias(perSecond(diamond.holyoke.holy-slurm02.sdiag.bf_total_jobs_since_cycle_start), 'Backfill Jobs Started per second')"
    }
   ]
  },
  {
   "title": "Total Backfill Cycles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"bf_total_cycles\"}",
     "legendFormat": "Backfill scheduling cycles",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.bf_total_cycles, 'Backfill scheduling cycles')"
    }
   ]
  },
  {
   "title": "Last/Mean Backfill Cycle Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"bf_last_cycle\"}",
     "legendFormat": "Time of last backfiling cycle",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.bf_last_cycle, 'Time of last backfilling cycle')"
    },
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"bf_mean_cycle\"}",
     "legendFormat": "Mean of backfilling scheduling cycles",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.bf_mean_cycle, 'Mean of backfilling scheduling cycles')"
    }
   ]
  },
  {
   "title": "Last Depth Cycle",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"bf_last_depth_cycle\"}",
     "legendFormat": "Processed jobs during last backfill",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.bf_last_depth_cycle, 'Processed jobs during last backfill')"
    },
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"bf_last_depth_cycle_try\"}",
     "legendFormat": "Processed jobs during last backfill (try sched)",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.bf_last_depth_cycle_try, 'Processed jobs during last backfill (try sched)')"
    }
   ]
  },
  {
   "title": "Last Backfill Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sdiag{host=\"slurm-test\", field=\"bf_queue_length\"}",
     "legendFormat": "Jobs pending backfill processing",
     "target": "alias(diamond.holyoke.holy-slurm02.sdiag.bf_queue_length, 'Jobs pending backfill processing')"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  }
 ]
}