{
 "title": "Partition Usage",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": { "query": "label_values(spart,host)" } },
   { "name": "Partition", "query": { "query": "label_values(spart,partition)" } }
  ]
 },
 "panels": [
  {
   "title": "Partition Usage",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Description**\n\nShows status of specific partition in a specific cluster.\n\nTo select a Cluster use the following mapping for the slurm masters:\n\n**Cannon**: holy-slurm02\n\n**FASSE**: fasse-slurm01\n\n**Test**: slurm-test\n\nYou can then select the partition you are interested in.\n\n**Percent Utilization**\n\nThis is the amount of the cluster that is utilized based on the average Occupation.\n\n**Occupation**\n\nSince looking at pure core, memory, or gpu allocation is misleading in terms of actual cluster usage, this plot shows occupation instead.  Occupation is `MAX(CPUAlloc/CPUTot, MemAlloc/MemTot, GPUAlloc/GPUTot)` summed across all the nodes for jobs in the selected partition.  The idea is that a node that has its memory fully utilized effectively has all its cores used as you can't schedule any more jobs.  Similarly a node that has all its cores used cannot allocate any memory even though it is available. For a GPU node, a full usage of the GPU's is effectively full occupation even if the CPU and memory are not fully used.  This metric should hopefully provide a better estimate of partition usage.  Ideally it should be equal to the number of nodes (assuming no down nodes).\n\n**Reserved Nodes**: How many nodes are in RESERVED state.\n\n**Down Nodes**: How many nodes are in DOWN or DRAIN state.\n\n**Job Stats**\n\nThis shows how many jobs are pending and running in a partition. It also shows how many total restarts across all the jobs for a partition. Jobs may restart due to node failure or if they are part of a preemptable partition they may be requeued.\n\n**Core/Memory/GPU Usage**\n\nShows the amount of cores/memory that are allocated and in use. In addition these graphs show usage from partitions that are higher PriorityTier than the current partition and lower PriorityTier than the current partition. This allows users to see if work from other partitions may be blocking the current partition, and also how many spare cycles are being picked up by lower priority partitions."
   }
  },
  {
   "title": "Percent Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Occupation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"node\"}",
     "legendFormat": "Total Number of Nodes"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"occ\"}",
     "legendFormat": "Node Occupation"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"resnode\"}",
     "legendFormat": "Reserved Nodes"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"downnode\"}",
     "legendFormat": "Down Nodes"
    }
   ]
  },
  {
   "title": "Job Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"pendcnt\"}",
     "legendFormat": "Pending Jobs"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"runcnt\"}",
     "legendFormat": "Running Jobs"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"restarts\"}",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"cpu\"}",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"runcpu\"}",
     "legendFormat": "Allocated Cores"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"rescpu\"}",
     "legendFormat": "Cores Reserved"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"downcpu\"}",
     "legendFormat": "Cores Down"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"hcpu\"}",
     "legendFormat": "Cores Allocted to High Priority Partitions"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"lcpu\"}",
     "legendFormat": "Cores Allocated to Lower Priority Partitions"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"mem\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"runmem\"}",
     "legendFormat": "Allocated Memory"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"resmem\"}",
     "legendFormat": "Memory Reserved"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"downmem\"}",
     "legendFormat": "Memory Down"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"hmem\"}",
     "legendFormat": "Memory Allocated to High Priority Partitions"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"lmem\"}",
     "legendFormat": "Memory Allocated to Lower Priority Partitions"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"gpu\"}",
     "legendFormat": "Total GPUs"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"rungpu\"}",
     "legendFormat": "Allocated GPUs"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"resgpu\"}",
     "legendFormat": "GPUs Reserved"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"downgpu\"}",
     "legendFormat": "GPUs Down"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"hgpu\"}",
     "legendFormat": "GPUs Allocated to High Priority Partitions"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"lgpu\"}",
     "legendFormat": "GPUs Allocated to Lower Priority Partitions"
    }
   ]
  },
  {
   "title": "TRES",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "These graphs show effective TRES usage.\n\nTRES is based off the TRESBillingWeights for the partition.  This includes core, gpu, and memory TRES.  This should give a better view of our actual compute capability."
   }
  },
  {
   "title": "Total TRES Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"trestot\"}",
     "legendFormat": "Total TRES"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"tresruntot\"}",
     "legendFormat": "Allocated TRES"
    }
   ]
  },
  {
   "title": "CPU TRES Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"trescpu\"}",
     "legendFormat": "Total TRES"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"tresruncpu\"}",
     "legendFormat": "Allocated TRES"
    }
   ]
  },
  {
   "title": "Memory TRES Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"tresmem\"}",
     "legendFormat": "Total TRES"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"tresrunmem\"}",
     "legendFormat": "Allocated TRES"
    }
   ]
  },
  {
   "title": "GPU TRES Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"tresgpu\"}",
     "legendFormat": "Total TRES"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"tresrungpu\"}",
     "legendFormat": "Allocated TRES"
    }
   ]
  },
  {
   "title": "FLOps",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "These graphs show effective FLOps usage.\n\nFLOps is based on our translation from TRES to GFLOps. This only includes core and gpu. This is based on theoretic peak, not actual GFLOps so numbers should be taken with a grain of salt.\n\n**WARNING** These numbers will be incorrect for mosaic (i.e. heterogeneous) and requeue partitions. This is due to the TRESBillingWeights for these specific partition (which the FLOps estimate is based on)  not correctly reflecting performance. In the case of a mosaic partition the TRESBillingWeight is usually an aggregate number for the variety of hardware in the partition and thus is not true on a per node basis but true in aggregate. For the requeue partitions we have a uniform TRESBillingWeight regardless of hardware that is also modified to be half the average weight of the hardware in the cluster. Thus the FLOps numbers for these partitions will be inaccurate and should not be quoted or used.\n"
   }
  },
  {
   "title": "Total FLOps Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "gflops" } },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"flopstot\"}",
     "legendFormat": "Total FLOps"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"flopsruntot\"}",
     "legendFormat": "Allocated FLOps"
    }
   ]
  },
  {
   "title": "CPU FLOps Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "gflops" } },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"flopscpu\"}",
     "legendFormat": "Total FLOps"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"flopsruncpu\"}",
     "legendFormat": "Allocated FLOps"
    }
   ]
  },
  {
   "title": "GPU FLOps Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "gflops" } },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"flopsgpu\"}",
     "legendFormat": "Total FLOps"
    },
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"flopsrungpu\"}",
     "legendFormat": "Allocated FLOps"
    }
   ]
  },
  { "title": "User Stats", "type": "text", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 }, "options": { "content": "Break down of usage per user." } },
  {
   "title": "Pending Jobs per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"penduser\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Running Jobs per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"runuser\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Core Usage per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"cpuuser\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Memory Usage per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"memuser\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "GPU Usage per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"gpuuser\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "TRES Usage per User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"tresuser\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Account Stats",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 80 },
   "options": {
    "content": "Break down of usage per account. Note that this is the account that the job is billing not the default account/group for the user."
   }
  },
  {
   "title": "Pending Jobs per Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"pendacct\"}",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Running Jobs per Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"runacct\"}",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Core Usage per Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"cpuacct\"}",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"memacct\"}",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "GPU Usage per Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"gpuacct\"}",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "TRES Usage per Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "spart{host=\"$Cluster\", partition=\"$Partition\", field=\"tresacct\"}",
     "legendFormat": "{{account}}"
    }
   ]
  }
 ]
}