{
 "title": "Test Cluster Fairshare",
 "tags": [
  "Slurm",
  "Production"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Cluster Fairshare",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Description**\n\nShows usage stats for all users.\n\n**Fairshare**\n\nShows fairshare score for all users. Fairshare can be broken down into a couple different regimes:\n\n**1.0**: Perfect. User has not run any jobs recently.\n\n**1.0 > x > 0.5**: Good. User is underutilizing their allocation.\n\n**0.5**: Ideal. User is using exactly as much as they have been allocated.\n\n**0.5 > x > 0**: Poor.  User has overused the their allocation.\n\n**0**: Abyssmal. User has vastly overused their allocation.\n\n**First Derivative of Fairshare**\n\nThe Fairshare rate of change per minute (as we are sampling the data on a per minute basis).  Note this is nonlinear in response to usage."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fairshare",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(sshare{host=\"slurm-test\", field=\"fairshare\"})",
     "legendFormat": "Average Fairshare",
     "target": "averageSeries(diamond.holyoke.holy-slurm02.sshare.*.*.fairshare)"
    }
   ]
  },
  {
   "title": "1st Derivative of Fairshare",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(idelta(sshare{host=\"slurm-test\", field=\"fairshare\"}[$__interval]))",
     "legendFormat": "{{label_name}}",
     "target": "derivative(averageSeries(diamond.holyoke.holy-slurm02.sshare.*.*.fairshare))"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "**Norm Usage**\n\nThis is the percentage of the total compute the user has used.  Norm Usage equal to Norm Shares gives Fairshare of 0.5.  Note this is aggregate including age half-life.\n\n**1st Derivative of Norm Usage**\n\nThe Norm Usage rate of change per minute.\n\n**Raw Usage**\n\nUsage in TRES Seconds for all users.  Note this is aggregate including age half-life  \n\n**1st Derivative of Raw Usage**\n\nThe Raw Usage rate of change per minute."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Norm Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sshare{host=\"slurm-test\", field=\"normusage\"}",
     "legendFormat": "__auto",
     "target": "highestCurrent(diamond.holyoke.holy-slurm02.sshare.*.*.normusage, 30)"
    }
   ]
  },
  {
   "title": "1st Derivative of Norm Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(sshare{host=\"slurm-test\", field=\"normusage\"}[$__interval])",
     "legendFormat": "__auto",
     "target": "averageSeries(derivative(diamond.holyoke.holy-slurm02.sshare.*.*.normusage))"
    }
   ]
  },
  {
   "title": "Raw Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sshare{host=\"slurm-test\", field=\"rawusage\"}",
     "legendFormat": "__auto",
     "target": "highestCurrent(diamond.holyoke.holy-slurm02.sshare.*.*.rawusage, 30)"
    }
   ]
  },
  {
   "title": "1st Derivative of Raw Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(sshare{host=\"slurm-test\", field=\"rawusage\"}[$__interval])",
     "legendFormat": "__auto",
     "target": "averageSeries(derivative(diamond.holyoke.holy-slurm02.sshare.*.*.rawusage))"
    }
   ]
  },
  {
   "title": "Shares",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "**Raw Shares**\n\nNumber of shares a user has been granted.  Ideally equal to the number of cores they have been allocated.  This demands that the totally number of shares equals the total number of cores in the cluster.\n\n**Norm Shares**\n\nFraction of the cluster the user has been granted.  This is RawShares divided by the sum of the Raw Shares."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Raw Shares",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sshare{host=\"slurm-test\", field=\"rawshares\"}",
     "legendFormat": "__auto",
     "target": "highestCurrent(diamond.holyoke.holy-slurm02.sshare.*.*.rawshares, 30)"
    }
   ]
  },
  {
   "title": "NormShares",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sshare{host=\"slurm-test\", field=\"normshares\"}",
     "legendFormat": "__auto",
     "target": "highestCurrent(diamond.holyoke.holy-slurm02.sshare.*.*.normshares, 30)"
    }
   ]
  }
 ]
}